name: Sync legacy master branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Move master to main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Push master
        run: git push origin HEAD:refs/heads/master --force
